### ISSUE TITLE
Bulgarian alphabet

### ISSUE THREAD

**Issue by iliev72** [nick-buhro/Translit#13]
It's possible to add Bulgarian alphabet ?!
https://en.wikipedia.org/wiki/Bulgarian_alphabet
https://en.wikipedia.org/wiki/Romanization_of_Bulgarian

**Comment by nick-buhro** [comment]
Hi, @iliev72! Bulgarian language has already supported:
``` C#
const string original = @"Всички хора се раждат свободни и равни по достойнство и права.";
var translit = Transliteration.CyrillicToLatin(original, Language.Bulgarian);
Console.WriteLine(translit);  // Output: "Vsichki xora se razhdat svobodni i ravni po dostojnstvo i prava."
```
As I see from your links, there are multiple standards for this operation, but the library supports only ISO 9 Type B.
