### ISSUE TITLE
Incorrect detection of Cyrillic symbols

### ISSUE THREAD

**Issue by beta-tank** [nick-buhro/Translit#5]
When I invoke `Transliteration.CyrillicToLatin("Obstacles")`, I got two matches:

> Obz
>taclez

instead of source latin string

**Comment by beta-tank** [comment]
I get source `Obstacles` string if set language to `Russian`, but didn't work with `Macedonian`

**Comment by nick-buhro** [comment]
It's because Macedonian alphabet contains letter `S`. So this letter transliterates to ``Z` ``.
