### ISSUE TITLE
Allow overriding ` as placeholder character

### ISSUE THREAD

**Issue by cypressious** [nick-buhro/Translit#7]
Some characters like 'ь' are transliterated to '`' which is ok but in some cases, e.g. in URLs it makes more sense to use a different character, e.g. '_'. Can you provide an option to override the placeholder character?

**Comment by nick-buhro** [comment]
It is reasonable issue but I don't see the way how to do it simple and clear in the library. In this situation I would recommend to write explicit code. And custom class/method could be defined for using same custom converter across all your application.
```C#
// Example: special converter for input character
var actual = Transliteration.CyrillicToLatin(
    cyrillicText.Replace('ь', '_'),
    Language.Russian);
```
```C#
// Example: special converter for output character
var actual = Transliteration
    .CyrillicToLatin(cyrillicText, Language.Russian);
    .Replace('`', '_');
```
```C#
// Example: custom convert method
public static void MyCyrillicToLatin(string source)
{
    return Transliteration
        .CyrillicToLatin(source, Language.Russian);
        .Replace('`', '_');
}
```
